--
-- PostgreSQL database dump
--

\restrict RhXobQ0y58lu7Zs2aqsNUcp7mDw5exgx8l0FKwLfQsvgxLipYK5DxFjckVVI4QL

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: update_timestamp(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_timestamp() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.update_timestamp() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: ingredientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ingredientes (
    id_ingrediente integer NOT NULL,
    nombre character varying(100) NOT NULL,
    unidad_base character varying(20)
);


ALTER TABLE public.ingredientes OWNER TO postgres;

--
-- Name: ingredientes_id_ingrediente_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ingredientes ALTER COLUMN id_ingrediente ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.ingredientes_id_ingrediente_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: receta_ingredientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.receta_ingredientes (
    id_receta_ingrediente integer NOT NULL,
    id_receta integer NOT NULL,
    id_ingrediente integer NOT NULL,
    cantidad numeric(10,2) NOT NULL,
    unidad character varying(20)
);


ALTER TABLE public.receta_ingredientes OWNER TO postgres;

--
-- Name: receta_ingredientes_id_receta_ingrediente_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.receta_ingredientes ALTER COLUMN id_receta_ingrediente ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.receta_ingredientes_id_receta_ingrediente_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recetas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recetas (
    id_receta integer NOT NULL,
    nombre character varying(150) NOT NULL,
    id_tipo_comida integer NOT NULL,
    estado smallint DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.recetas OWNER TO postgres;

--
-- Name: recetas_id_receta_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recetas ALTER COLUMN id_receta ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.recetas_id_receta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id_rol integer NOT NULL,
    nombre character varying(50) NOT NULL,
    descripcion character varying(255)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id_rol ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.roles_id_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipos_comida; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipos_comida (
    id_tipo_comida integer NOT NULL,
    nombre character varying(50) NOT NULL
);


ALTER TABLE public.tipos_comida OWNER TO postgres;

--
-- Name: tipos_comida_id_tipo_comida_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipos_comida ALTER COLUMN id_tipo_comida ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tipos_comida_id_tipo_comida_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id_usuario integer NOT NULL,
    nombre character varying(100) NOT NULL,
    correo character varying(120) NOT NULL,
    password_hash character varying(255) NOT NULL,
    id_rol integer NOT NULL,
    estado smallint DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id_usuario ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add auth group	7	add_authgroup
26	Can change auth group	7	change_authgroup
27	Can delete auth group	7	delete_authgroup
28	Can view auth group	7	view_authgroup
29	Can add auth group permissions	8	add_authgrouppermissions
30	Can change auth group permissions	8	change_authgrouppermissions
31	Can delete auth group permissions	8	delete_authgrouppermissions
32	Can view auth group permissions	8	view_authgrouppermissions
33	Can add auth permission	9	add_authpermission
34	Can change auth permission	9	change_authpermission
35	Can delete auth permission	9	delete_authpermission
36	Can view auth permission	9	view_authpermission
37	Can add auth user	10	add_authuser
38	Can change auth user	10	change_authuser
39	Can delete auth user	10	delete_authuser
40	Can view auth user	10	view_authuser
41	Can add auth user groups	11	add_authusergroups
42	Can change auth user groups	11	change_authusergroups
43	Can delete auth user groups	11	delete_authusergroups
44	Can view auth user groups	11	view_authusergroups
45	Can add auth user user permissions	12	add_authuseruserpermissions
46	Can change auth user user permissions	12	change_authuseruserpermissions
47	Can delete auth user user permissions	12	delete_authuseruserpermissions
48	Can view auth user user permissions	12	view_authuseruserpermissions
49	Can add django admin log	13	add_djangoadminlog
50	Can change django admin log	13	change_djangoadminlog
51	Can delete django admin log	13	delete_djangoadminlog
52	Can view django admin log	13	view_djangoadminlog
53	Can add django content type	14	add_djangocontenttype
54	Can change django content type	14	change_djangocontenttype
55	Can delete django content type	14	delete_djangocontenttype
56	Can view django content type	14	view_djangocontenttype
57	Can add django migrations	15	add_djangomigrations
58	Can change django migrations	15	change_djangomigrations
59	Can delete django migrations	15	delete_djangomigrations
60	Can view django migrations	15	view_djangomigrations
61	Can add django session	16	add_djangosession
62	Can change django session	16	change_djangosession
63	Can delete django session	16	delete_djangosession
64	Can view django session	16	view_djangosession
65	Can add ingredientes	17	add_ingredientes
66	Can change ingredientes	17	change_ingredientes
67	Can delete ingredientes	17	delete_ingredientes
68	Can view ingredientes	17	view_ingredientes
69	Can add receta ingredientes	18	add_recetaingredientes
70	Can change receta ingredientes	18	change_recetaingredientes
71	Can delete receta ingredientes	18	delete_recetaingredientes
72	Can view receta ingredientes	18	view_recetaingredientes
73	Can add recetas	19	add_recetas
74	Can change recetas	19	change_recetas
75	Can delete recetas	19	delete_recetas
76	Can view recetas	19	view_recetas
77	Can add roles	20	add_roles
78	Can change roles	20	change_roles
79	Can delete roles	20	delete_roles
80	Can view roles	20	view_roles
81	Can add tipos comida	21	add_tiposcomida
82	Can change tipos comida	21	change_tiposcomida
83	Can delete tipos comida	21	delete_tiposcomida
84	Can view tipos comida	21	view_tiposcomida
85	Can add usuarios	22	add_usuarios
86	Can change usuarios	22	change_usuarios
87	Can delete usuarios	22	delete_usuarios
88	Can view usuarios	22	view_usuarios
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	apps	authgroup
8	apps	authgrouppermissions
9	apps	authpermission
10	apps	authuser
11	apps	authusergroups
12	apps	authuseruserpermissions
13	apps	djangoadminlog
14	apps	djangocontenttype
15	apps	djangomigrations
16	apps	djangosession
17	apps	ingredientes
18	apps	recetaingredientes
19	apps	recetas
20	apps	roles
21	apps	tiposcomida
22	apps	usuarios
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-11-30 04:12:11.439873+00
2	auth	0001_initial	2025-11-30 04:12:11.493153+00
3	admin	0001_initial	2025-11-30 04:12:11.507543+00
4	admin	0002_logentry_remove_auto_add	2025-11-30 04:12:11.511417+00
5	admin	0003_logentry_add_action_flag_choices	2025-11-30 04:12:11.516079+00
6	contenttypes	0002_remove_content_type_name	2025-11-30 04:12:11.527118+00
7	auth	0002_alter_permission_name_max_length	2025-11-30 04:12:11.531918+00
8	auth	0003_alter_user_email_max_length	2025-11-30 04:12:11.536+00
9	auth	0004_alter_user_username_opts	2025-11-30 04:12:11.540401+00
10	auth	0005_alter_user_last_login_null	2025-11-30 04:12:11.545505+00
11	auth	0006_require_contenttypes_0002	2025-11-30 04:12:11.546906+00
12	auth	0007_alter_validators_add_error_messages	2025-11-30 04:12:11.551022+00
13	auth	0008_alter_user_username_max_length	2025-11-30 04:12:11.561447+00
14	auth	0009_alter_user_last_name_max_length	2025-11-30 04:12:11.566337+00
15	auth	0010_alter_group_name_max_length	2025-11-30 04:12:11.57152+00
16	auth	0011_update_proxy_permissions	2025-11-30 04:12:11.57498+00
17	auth	0012_alter_user_first_name_max_length	2025-11-30 04:12:11.579278+00
18	sessions	0001_initial	2025-11-30 04:12:11.585982+00
19	apps	0001_initial	2025-11-30 17:29:17.654804+00
20	apps	0002_alter_tiposcomida_options	2025-12-08 21:15:03.405003+00
21	apps	0002_recetas_idx_receta_nombre_and_more	2026-02-07 01:26:44.291912+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
i80zprz5wfosx6vf9mtc2qeadlnvee7v	.eJyrViotLk0sysyPz0xRsjLSgXPz8nOTilKVrJScUvOyEnMz8xSCE3MSqxKLlBBqivJzlKwMawFNohhW:1vQuwJ:YotRRuU7I1hXIIOC0LxErkW8Kn69Y2dt0UPa8JO_E3w	2025-12-17 22:03:11.294363+00
pfudjjuq42ux8lztivr70tzxoz5kpk56	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vQvrx:QpL5gq-JebabUT3LY6xFvp7EtWHDmIEJX3J8RfpPkWI	2025-12-17 23:02:45.642581+00
sml1mafkbmobmsmaq43z1v6htszl1s8e	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vQxZG:d4uHibw4xs94E-B94WZnN6PeldnTrF9_hfwl80tW6vE	2025-12-18 00:51:34.281902+00
wb0kzrywhpd900m6m8t635vykyr7n1s8	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vRJ0g:Ojr1ruqw8PyFG-yuOaiseW_62wlGpXK6ti7Glo-ItUQ	2025-12-18 23:45:18.298228+00
cwb49f3vg6qkqftma3o0zfeq3w9bkzob	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vRK10:PsSlNo8jP6t8r_q6hWuDRNAOQFRBWUhTrp96P5lO_vo	2025-12-19 00:49:42.634141+00
6vajqtdi78bgu8mpygzh1srfjmr7euts	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkRz:IKpoFNvO3vAQ-x2OQObNuGmtWfG4i1gl_mPCISe6fzc	2025-12-22 23:15:27.949748+00
ferz6laviv4g4jvs476ki3d6wg5qfjee	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkRz:IKpoFNvO3vAQ-x2OQObNuGmtWfG4i1gl_mPCISe6fzc	2025-12-22 23:15:27.981762+00
1k6ip3cr8jqhagsqqgdvz5qkf0xya2hv	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS0:V2ycu0Yma425E2e_fRfpS75HMOrcAi8ztwDdOPhd0N0	2025-12-22 23:15:28.289459+00
8gd4o1dyvjn16ynscgu9u5ejuej8b5rx	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS0:V2ycu0Yma425E2e_fRfpS75HMOrcAi8ztwDdOPhd0N0	2025-12-22 23:15:28.357194+00
rk5v4xsdqi1mkl27brhu2zkvrknv5yku	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS0:V2ycu0Yma425E2e_fRfpS75HMOrcAi8ztwDdOPhd0N0	2025-12-22 23:15:28.678222+00
tpo9t3yewg67vqhlhumfu909osbsh3e1	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS1:mHeA8FtAlxdfLEo-xGzovZCnsVKps8lbIx_jv99utuc	2025-12-22 23:15:29.052941+00
l02tnjvwmucutfc6n2l0l9vzsyruv7j5	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS1:mHeA8FtAlxdfLEo-xGzovZCnsVKps8lbIx_jv99utuc	2025-12-22 23:15:29.080906+00
qeohef4q1484nf2vclg5tz64q70i20e6	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS1:mHeA8FtAlxdfLEo-xGzovZCnsVKps8lbIx_jv99utuc	2025-12-22 23:15:29.115554+00
gd75z10mv86y4htibtym35lp8kiyq6mf	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS1:mHeA8FtAlxdfLEo-xGzovZCnsVKps8lbIx_jv99utuc	2025-12-22 23:15:29.426569+00
qobehhg2qqsoacymozavgq4z5m6qucjo	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS1:mHeA8FtAlxdfLEo-xGzovZCnsVKps8lbIx_jv99utuc	2025-12-22 23:15:29.471326+00
505ma6fqoqor26bsg88mao39tfofihz0	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS2:sQJoEnPOYBfeciKW9PbhulJb69pNjpWl1odssyk2rJg	2025-12-22 23:15:30.254322+00
70o4op0yr33cbaa68x7ar2oq6ap00ygu	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS2:sQJoEnPOYBfeciKW9PbhulJb69pNjpWl1odssyk2rJg	2025-12-22 23:15:30.347359+00
1fno8vcmgoarc9xp4ib0ls74am6wdchj	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS2:sQJoEnPOYBfeciKW9PbhulJb69pNjpWl1odssyk2rJg	2025-12-22 23:15:30.755817+00
qx7cya0tf2igc3dfnywek0khd9ybcy17	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS2:sQJoEnPOYBfeciKW9PbhulJb69pNjpWl1odssyk2rJg	2025-12-22 23:15:30.834603+00
i20mfm1hewszw22lg8pied291xf3v9gn	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS3:fiN6R2nP8YSrNL-hLBQqTpKH8gL-t_-6Ri3GFFXyz_4	2025-12-22 23:15:31.020145+00
aklxetki05wffqv25n20ysbq611dt18s	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS3:fiN6R2nP8YSrNL-hLBQqTpKH8gL-t_-6Ri3GFFXyz_4	2025-12-22 23:15:31.435506+00
k4diwg87564b489pcwy5ty58pg6n8xq4	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS3:fiN6R2nP8YSrNL-hLBQqTpKH8gL-t_-6Ri3GFFXyz_4	2025-12-22 23:15:31.536274+00
8h7j17qm6cpe3967nv370gturxjflmhp	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS3:fiN6R2nP8YSrNL-hLBQqTpKH8gL-t_-6Ri3GFFXyz_4	2025-12-22 23:15:31.578949+00
x1pe9mlf7po9jrt917rr4t8mog6x37pv	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS3:fiN6R2nP8YSrNL-hLBQqTpKH8gL-t_-6Ri3GFFXyz_4	2025-12-22 23:15:31.698363+00
hthzlm7hblcu8jads6yldkr298s560d4	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS3:fiN6R2nP8YSrNL-hLBQqTpKH8gL-t_-6Ri3GFFXyz_4	2025-12-22 23:15:31.747972+00
jblh5vcbvlme2wjzjzxwl9r1ycwtw0ho	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS4:r-kN_5zgmrPz-KrYxZyp_yd6Zg_LI-BfjOjv5Rp5Nj4	2025-12-22 23:15:32.465499+00
0728slrqscqh4raonrrdfcj512wzx5bu	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS4:r-kN_5zgmrPz-KrYxZyp_yd6Zg_LI-BfjOjv5Rp5Nj4	2025-12-22 23:15:32.57499+00
1awutuoqpccrbfrfm0hsrkan4m4v8o0d	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS4:r-kN_5zgmrPz-KrYxZyp_yd6Zg_LI-BfjOjv5Rp5Nj4	2025-12-22 23:15:32.624295+00
sc9wfyy0xdtg2j1j4y5g3ihhr8q4c4cs	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS4:r-kN_5zgmrPz-KrYxZyp_yd6Zg_LI-BfjOjv5Rp5Nj4	2025-12-22 23:15:32.73389+00
m28sgmowbxug7szriz3xl1wf4kdsf6tv	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS4:r-kN_5zgmrPz-KrYxZyp_yd6Zg_LI-BfjOjv5Rp5Nj4	2025-12-22 23:15:32.866957+00
6b7d2vzu0fjrx46ur0vehk01fit2xgqw	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS5:YJ224FTGkOon5RDW9c0E-9FdFOmwn3qXRw_FoOMLJhI	2025-12-22 23:15:33.430469+00
fq0lz4ldtwrsp2vsnqf8635rotck9hs1	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS5:YJ224FTGkOon5RDW9c0E-9FdFOmwn3qXRw_FoOMLJhI	2025-12-22 23:15:33.473663+00
1xy0mbxvmdny71dzxw0hutih99kw6dg7	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS5:YJ224FTGkOon5RDW9c0E-9FdFOmwn3qXRw_FoOMLJhI	2025-12-22 23:15:33.478999+00
mcefoqod1okezcoq9vvbg5t4vdyx8kp4	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS5:YJ224FTGkOon5RDW9c0E-9FdFOmwn3qXRw_FoOMLJhI	2025-12-22 23:15:33.533855+00
ruwxzx1sj1amswxfr206in3dhg98ks4h	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS5:YJ224FTGkOon5RDW9c0E-9FdFOmwn3qXRw_FoOMLJhI	2025-12-22 23:15:33.708363+00
uymj1ljgef4eew7tmg3fk3gkcga494cb	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS6:ZMQEjpMg86jQ7qKgpJTPsQWMS8KxeDmkNEMORpxhLzU	2025-12-22 23:15:34.599357+00
ec8f2xvaxw5f15e3ezac056g23pfmkd5	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS6:ZMQEjpMg86jQ7qKgpJTPsQWMS8KxeDmkNEMORpxhLzU	2025-12-22 23:15:34.601592+00
6hm28x3s87770lb8omjr2ib53tc8z1gd	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS6:ZMQEjpMg86jQ7qKgpJTPsQWMS8KxeDmkNEMORpxhLzU	2025-12-22 23:15:34.926211+00
ppkky7mmske045oe9izzd291tnrb8bwy	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS7:vca5241Kbu9tAhkonx9Bb6Gzd2bkN0eGSDW1Y4YvWng	2025-12-22 23:15:35.042362+00
ixjfp34g1z7sxufhe2tv3aepvwun4lk2	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS7:vca5241Kbu9tAhkonx9Bb6Gzd2bkN0eGSDW1Y4YvWng	2025-12-22 23:15:35.134738+00
js0pggsqv5sc80d2l6zb0hw848ulrko9	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS7:vca5241Kbu9tAhkonx9Bb6Gzd2bkN0eGSDW1Y4YvWng	2025-12-22 23:15:35.457643+00
yhs6mp9336h9vmlmr70ujoz7t0w4feia	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS7:vca5241Kbu9tAhkonx9Bb6Gzd2bkN0eGSDW1Y4YvWng	2025-12-22 23:15:35.576815+00
hllzkgmuoj2ymjzj2qvmq16o2tri7chp	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS7:vca5241Kbu9tAhkonx9Bb6Gzd2bkN0eGSDW1Y4YvWng	2025-12-22 23:15:35.702123+00
rm0mzmjdnoryipj8fseh8vq4x4wjgexn	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS7:vca5241Kbu9tAhkonx9Bb6Gzd2bkN0eGSDW1Y4YvWng	2025-12-22 23:15:35.752879+00
ncdc0gfjyhsyrgmvagzwqud95yrlio36	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS7:vca5241Kbu9tAhkonx9Bb6Gzd2bkN0eGSDW1Y4YvWng	2025-12-22 23:15:35.833845+00
z14501iew96yhigt7id5002by4e5h1t2	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS8:1ZVYgNlodLDKbo_YKPq3SmXMKIpTWHFctR_5nbPppaA	2025-12-22 23:15:36.556338+00
vlest7qhtrjwum52kkd1xofm4q8gchl5	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS8:1ZVYgNlodLDKbo_YKPq3SmXMKIpTWHFctR_5nbPppaA	2025-12-22 23:15:36.575445+00
r6paob2f8i9qjnxzltruljy0qp8mrxlp	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS8:1ZVYgNlodLDKbo_YKPq3SmXMKIpTWHFctR_5nbPppaA	2025-12-22 23:15:36.628196+00
zvx8wrplv54cvzcplw5ff1pktfff42ze	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS8:1ZVYgNlodLDKbo_YKPq3SmXMKIpTWHFctR_5nbPppaA	2025-12-22 23:15:36.629943+00
r75cdij3nz3lijt40594rtr0k3r9vc4d	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS8:1ZVYgNlodLDKbo_YKPq3SmXMKIpTWHFctR_5nbPppaA	2025-12-22 23:15:36.652411+00
t5m9vij9x69pqx2rsts518gcksyrkje8	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS9:Lor9bksUNYA5RNz9ZhS2y622LDmmj7f2KiK1HtyuNt8	2025-12-22 23:15:37.084095+00
lze8cqvep7y2zvll4jkyp0pp4mr7trn3	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS9:Lor9bksUNYA5RNz9ZhS2y622LDmmj7f2KiK1HtyuNt8	2025-12-22 23:15:37.218783+00
k3iyk9sw81ujovwpw34gumtteun2h7q6	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS9:Lor9bksUNYA5RNz9ZhS2y622LDmmj7f2KiK1HtyuNt8	2025-12-22 23:15:37.232122+00
804oyid8u1nxqtymyi9r8ibr5srgxaon	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS9:Lor9bksUNYA5RNz9ZhS2y622LDmmj7f2KiK1HtyuNt8	2025-12-22 23:15:37.23756+00
11c1271wvz4gz33ecbxlggd8yvxtz7qu	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVka1AOmwFrQ:1vSkS9:Lor9bksUNYA5RNz9ZhS2y622LDmmj7f2KiK1HtyuNt8	2025-12-22 23:15:37.353889+00
p9antn14r25inrrn9z5655opgqkeq8ue	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVkY6SkWpxaW5qXnxRanJqSWJxUpW0bG1ABg2Hls:1vsAtj:vKLBXUc9pvNNrV83iefFfmnXMwlZPCg2ifbNv6m7ubc	2026-03-03 02:33:11.183236+00
u54xh6zx81ypnm2mflyxxt36s230r5fh	.eJyrViotLk0sysyPz0xRsjLSgXPz8nOTilKVrJScUvOyEnMz8xSCE3MSqxKLlBBqivJzlKwMawFNohhW:1vsXKo:GvgVLQDfop_6kn-Zm6GJjFp7oj6sO8--AnCO3sm78vI	2026-03-04 02:30:38.480185+00
5tpkqbvxl5jhol2dy2ygfx711ov2u0c3	.eJyrViotLk0sysyPz0xRsjLUgXPz8nOTilKVrJT8izIT8xIVfBLT84uVEPJF-TlKVkY6SkWpxaW5qXnxRanJqSWJxUpW0bG1ABg2Hls:1vrlws:_ezDD-JWc77HN236qcJDvfpyd5bwyef4__nqjoXw_Io	2026-03-01 23:54:46.421391+00
\.


--
-- Data for Name: ingredientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ingredientes (id_ingrediente, nombre, unidad_base) FROM stdin;
1	Aceite De Maravilla	ml
2	Aceituna 	gr
3	Acelga	gr
4	Ajo	gr
5	Albahaca	gr
6	Arroz	gr
7	Arvejas Congeladas Cocidas	gr
8	Avena	gr
9	Berenjena	gr
10	Caldo Concentrado	gr
11	Cebolla	gr
12	Cebollín	gr
13	Champiñones	gr
14	Choclo Congelado	gr
15	Chocolate En Polvo	gr
52	Osobuco	gr
53	Palta	gr
54	Pan Tipo Marraqueta-Hallulla	gr
55	Papa Cruda	gr
56	Pastelera De Choclo	gr
57	Pechuga De Pollo	gr
58	Pepino	gr
59	Perejil	gr
60	Pickles	gr
61	Pimentón	gr
62	Platano	gr
63	Poroto Crudo	gr
64	Porotos Granados	gr
65	Porotos Verdes	gr
66	Posta rosada	gr
67	Primavera Frizada	gr
68	Pulpa De Cerdo	gr
69	Pure Papas Formula Completa	gr
70	Quesillo	gr
71	Queso Fresco	gr
72	Queso Gauda	gr
73	Queso Rallado	gr
74	Sal	gr
76	Salsa De Tomates	gr
77	Salsa Española	gr
78	Semillas de Chía	gr
79	Surtido De Mariscos Congelados	gr
80	Tomate	gr
81	Truto de pollo 1/4	gr
82	Vinagre	ml
83	Yogurt Natural	gr
84	Zanahoria	gr
85	Zapallo Camote	gr
86	Zapallo Italiano	gr
19	Curry	gr
20	Diente De Dragon	gr
21	Espinaca	gr
22	Fideos Crudos	gr
23	Frutilla	gr
24	Galletas Soda	gr
25	Garbanzo Crudo	gr
26	Harina Trigo	gr
31	Jurel Enlatado	gr
32	Leche En Polvo 18% Mat, grasa	gr
35	Lenteja Cruda	gr
36	Maicena	gr
37	Maní Tostado Sin Sal	gr
38	Manjar	gr
39	Manzana	gr
40	Margarina	gr
41	Masa Empanada 12 CMS	gr
42	Masa Fajitas	gr
43	Masa Lasaña	gr
44	Mayonesa	gr
45	Merluza	gr
46	Mermelada Sin Azucar	gr
47	Miel	gr
48	Mostaza	gr
49	Naranja	gr
50	Nuez	gr
51	Orégano	gr
16	Ciboulette	gr
17	Coliflor	gr
18	Crema De Leche	ml
27	Hígado Vacuno	gr
30	Jugo De Limón	ml
33	Leche En Polvo 26% Mat, grasa	gr
29	Jamón	gr
34	Leche Fluida Entera	ml
75	Salsa De Soya	ml
28	Huevo Entero	gr
\.


--
-- Data for Name: receta_ingredientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.receta_ingredientes (id_receta_ingrediente, id_receta, id_ingrediente, cantidad, unidad) FROM stdin;
67	76	1	5.00	ml
68	76	4	1.00	gr
69	76	10	0.30	gr
70	76	11	22.00	gr
71	76	26	5.00	gr
73	76	51	0.10	gr
74	76	54	10.00	gr
75	76	61	12.00	gr
76	76	66	94.00	gr
77	76	74	2.00	gr
78	76	76	20.00	gr
79	32	1	3.00	ml
80	32	6	70.00	gr
81	32	22	5.00	gr
82	32	74	2.00	gr
83	33	1	3.00	ml
84	33	4	1.00	gr
85	33	6	50.00	gr
86	33	7	20.00	gr
87	33	55	47.00	gr
88	33	74	2.00	gr
89	33	84	22.00	gr
90	33	85	33.00	gr
91	34	1	3.00	ml
92	34	6	70.00	gr
93	34	12	11.00	gr
94	34	74	2.00	gr
95	35	1	3.00	ml
96	35	4	1.00	gr
97	35	6	70.00	gr
98	35	12	5.00	gr
100	35	74	2.00	gr
101	35	84	3.00	gr
38	31	1	3.00	ml
39	31	3	125.00	gr
40	31	11	22.00	gr
41	31	18	20.00	ml
42	31	26	8.00	gr
43	31	33	8.00	gr
44	31	40	5.00	gr
45	31	74	2.00	gr
46	74	1	3.00	ml
47	74	2	3.00	gr
48	74	4	1.00	gr
49	74	11	22.00	gr
50	74	18	10.00	ml
187	81	1	8.00	ml
52	74	34	10.00	ml
53	74	54	8.00	gr
54	74	57	80.00	gr
55	74	61	4.00	gr
56	74	74	2.00	gr
57	75	1	8.00	ml
58	75	4	1.00	gr
59	75	11	20.00	gr
60	75	26	5.00	gr
62	75	54	10.00	gr
63	75	61	12.00	gr
64	75	66	94.00	gr
65	75	74	2.00	gr
66	75	84	6.00	gr
102	109	1	3.00	ml
103	109	4	1.00	gr
104	109	6	70.00	gr
105	109	7	15.00	gr
106	109	55	47.00	gr
107	109	61	1.00	gr
108	109	66	71.00	gr
109	109	74	2.00	gr
110	109	84	17.00	gr
111	36	1	3.00	ml
112	36	6	70.00	gr
113	36	19	3.00	gr
114	36	61	1.00	gr
115	36	74	2.00	gr
116	37	1	3.00	ml
117	37	4	1.00	gr
118	37	6	70.00	gr
119	37	11	11.00	gr
120	37	61	6.00	gr
121	37	74	2.00	gr
122	37	84	11.00	gr
123	38	1	3.00	ml
124	38	2	3.00	gr
125	38	4	1.00	gr
126	38	6	70.00	gr
127	38	74	2.00	gr
128	39	1	3.00	ml
129	39	4	1.00	gr
130	39	6	70.00	gr
131	39	74	2.00	gr
132	40	1	3.00	ml
133	40	6	70.00	gr
134	40	61	12.00	gr
135	40	74	2.00	gr
136	41	1	3.00	ml
137	41	6	70.00	gr
138	41	67	20.00	gr
139	41	74	2.00	gr
140	42	1	3.00	ml
141	42	6	70.00	gr
142	42	11	11.00	gr
143	42	60	8.00	gr
144	42	74	2.00	gr
145	43	1	3.00	ml
146	43	6	70.00	gr
147	43	59	6.00	gr
148	43	74	2.00	gr
149	77	1	8.00	ml
150	77	4	1.00	gr
151	77	7	30.00	gr
152	77	11	44.00	gr
153	77	61	1.00	gr
154	77	66	94.00	gr
155	77	74	2.00	gr
156	77	84	22.00	gr
157	78	1	5.00	ml
158	78	3	38.00	gr
159	78	4	1.00	gr
160	78	11	22.00	gr
162	78	54	20.00	gr
163	78	66	94.00	gr
164	78	74	2.00	gr
165	78	84	22.00	gr
166	79	1	5.00	ml
167	79	4	1.00	gr
168	79	11	22.00	gr
169	79	36	2.00	gr
171	79	61	1.00	gr
172	79	66	118.00	gr
173	79	74	2.00	gr
174	79	82	3.00	ml
170	79	51	0.10	gr
175	80	1	3.00	ml
176	80	3	50.00	gr
177	80	11	11.00	gr
179	80	33	5.00	gr
180	80	54	20.00	gr
181	80	61	2.00	gr
182	80	65	40.00	gr
183	80	67	40.00	gr
184	80	73	5.00	gr
185	80	74	2.00	gr
186	80	84	11.00	gr
188	81	4	1.00	gr
189	81	11	33.00	gr
190	81	51	0.00	gr
191	81	61	1.00	gr
192	81	66	118.00	gr
193	81	74	2.00	gr
194	81	82	3.00	ml
195	81	84	22.00	gr
196	83	1	5.00	ml
197	83	4	1.00	gr
198	83	11	33.00	gr
199	83	61	1.00	gr
200	83	66	118.00	gr
201	83	74	2.00	gr
202	83	84	34.00	gr
203	84	1	8.00	ml
204	84	11	11.00	gr
205	84	12	54.00	gr
206	84	66	106.00	gr
207	84	75	3.00	ml
208	44	1	5.00	ml
209	44	3	38.00	gr
210	44	11	22.00	gr
211	44	14	10.00	gr
212	44	55	235.00	gr
213	44	59	1.00	gr
214	44	61	1.00	gr
215	44	65	10.00	gr
216	44	74	2.00	gr
217	44	84	22.00	gr
218	44	85	54.00	gr
219	86	1	10.00	ml
220	86	18	10.00	ml
221	86	48	5.00	gr
222	86	51	0.10	gr
223	86	68	118.00	gr
224	86	74	1.00	gr
225	86	82	3.00	ml
226	87	1	5.00	ml
227	87	4	1.00	gr
228	87	11	33.00	gr
229	87	26	5.00	gr
231	87	54	20.00	gr
232	87	61	1.00	gr
233	87	66	47.00	gr
234	87	74	2.00	gr
235	88	1	5.00	ml
236	88	8	10.00	gr
237	88	11	6.00	gr
238	88	25	40.00	gr
240	88	74	1.00	gr
241	88	84	17.00	gr
242	45	1	3.00	ml
243	45	4	1.00	gr
244	45	6	40.00	gr
245	45	7	20.00	gr
246	45	14	20.00	gr
247	45	44	10.00	gr
248	45	74	2.00	gr
249	45	84	22.00	gr
250	89	1	10.00	ml
251	89	26	5.00	gr
253	89	29	30.00	gr
254	89	54	25.00	gr
255	89	66	59.00	gr
256	89	72	30.00	gr
257	89	74	1.00	gr
258	90	1	3.00	ml
259	90	40	3.00	gr
260	90	57	100.00	gr
261	90	74	2.00	gr
262	46	1	10.00	ml
263	46	3	250.00	gr
264	46	26	15.00	gr
266	46	54	5.00	gr
267	46	74	2.00	gr
268	47	1	10.00	ml
269	47	17	209.00	gr
270	47	26	15.00	gr
272	47	54	5.00	gr
273	47	74	2.00	gr
274	91	1	5.00	ml
275	91	4	1.00	gr
276	91	11	22.00	gr
277	91	26	3.00	gr
278	91	61	6.00	gr
279	91	66	94.00	gr
280	91	74	2.00	gr
281	91	76	10.00	gr
282	91	80	22.00	gr
283	110	1	5.00	ml
284	110	4	1.00	gr
285	110	11	33.00	gr
286	110	28	12.00	gr
287	110	55	176.00	gr
288	110	59	1.00	gr
289	110	61	1.00	gr
290	110	66	94.00	gr
291	110	74	2.00	gr
292	110	84	34.00	gr
293	48	1	5.00	ml
294	48	3	250.00	gr
295	48	4	1.00	gr
296	48	11	22.00	gr
297	48	28	25.00	gr
298	48	61	1.00	gr
299	48	74	2.00	gr
300	48	84	22.00	gr
301	92	1	5.00	ml
302	92	4	1.00	gr
303	92	11	22.00	gr
305	92	61	1.00	gr
306	92	66	94.00	gr
307	92	74	1.00	gr
308	92	84	22.00	gr
309	92	86	130.00	gr
310	111	1	8.00	ml
311	111	4	1.00	gr
312	111	11	33.00	gr
313	111	22	100.00	gr
314	111	26	5.00	gr
315	111	33	5.00	gr
316	111	40	1.00	gr
317	111	51	0.10	gr
318	111	57	80.00	gr
319	111	61	1.00	gr
320	111	72	30.00	gr
321	111	73	5.00	gr
322	111	74	2.00	gr
323	111	84	22.00	gr
324	49	1	10.00	ml
325	49	55	282.00	gr
326	49	74	2.00	gr
327	50	1	30.00	ml
328	50	55	200.00	gr
329	50	74	3.00	gr
330	51	1	3.00	ml
331	51	16	1.00	gr
332	51	40	5.00	gr
333	51	55	282.00	gr
334	51	73	8.00	gr
335	51	74	2.00	gr
336	52	4	1.00	gr
337	52	30	13.00	ml
338	52	40	5.00	gr
339	52	55	282.00	gr
340	52	59	1.00	gr
341	52	73	9.00	gr
342	52	74	2.00	gr
343	53	18	15.00	ml
344	53	22	70.00	gr
345	53	74	2.00	gr
346	54	1	1.00	ml
347	54	22	70.00	gr
348	54	74	2.00	gr
349	54	84	34.00	gr
350	55	1	1.00	ml
351	55	4	1.00	gr
352	55	5	1.00	gr
353	55	22	70.00	gr
354	55	50	3.00	gr
355	55	51	0.10	gr
356	55	73	5.00	gr
357	55	74	2.00	gr
358	56	1	1.00	ml
359	56	22	70.00	gr
360	56	74	2.00	gr
361	56	76	20.00	gr
362	112	22	70.00	gr
363	112	26	5.00	gr
364	112	29	15.00	gr
365	112	33	5.00	gr
366	112	40	5.00	gr
367	112	57	80.00	gr
368	112	73	5.00	gr
369	112	74	2.00	gr
370	57	1	1.00	ml
371	57	22	70.00	gr
372	57	74	2.00	gr
373	58	1	3.00	ml
374	58	4	1.00	gr
375	58	9	54.00	gr
376	58	22	60.00	gr
377	58	61	24.00	gr
378	58	74	2.00	gr
379	58	84	33.00	gr
380	59	7	10.00	gr
381	59	22	60.00	gr
382	59	29	10.00	gr
383	59	44	5.00	gr
384	59	59	1.00	gr
385	59	60	10.00	gr
386	59	74	2.00	gr
387	60	22	70.00	gr
388	60	28	13.00	gr
389	60	40	3.00	gr
390	60	73	5.00	gr
391	60	74	2.00	gr
392	61	1	1.00	ml
393	61	22	70.00	gr
394	61	61	24.00	gr
395	61	74	2.00	gr
396	61	84	11.00	gr
397	113	1	8.00	ml
398	113	2	3.00	gr
399	113	11	67.00	gr
400	113	28	25.00	gr
401	113	33	5.00	gr
402	113	40	5.00	gr
403	113	55	235.00	gr
404	113	66	82.00	gr
405	113	84	34.00	gr
406	114	1	8.00	ml
407	114	11	33.00	gr
408	114	30	13.00	ml
409	114	45	120.00	gr
410	114	55	176.00	gr
411	114	59	1.00	gr
412	114	61	1.00	gr
413	114	74	2.00	gr
414	93	40	3.00	gr
415	93	45	150.00	gr
416	93	74	2.00	gr
417	93	84	22.00	gr
418	94	1	20.00	ml
419	94	26	5.00	gr
420	94	28	25.00	gr
421	94	54	20.00	gr
422	94	57	80.00	gr
423	94	74	1.00	gr
424	95	1	3.00	ml
425	95	30	11.00	ml
426	95	74	2.00	gr
427	95	81	235.00	gr
428	96	1	5.00	ml
429	96	2	5.00	gr
430	96	5	2.00	gr
431	96	40	5.00	gr
432	96	57	100.00	gr
433	96	65	20.00	gr
434	96	74	2.00	gr
435	96	80	22.00	gr
436	115	1	10.00	ml
437	115	4	5.00	gr
438	115	11	56.00	gr
439	115	22	30.00	gr
440	115	63	40.00	gr
441	115	85	65.00	gr
442	62	1	2.00	ml
443	62	3	44.00	gr
444	62	33	5.00	gr
445	62	40	5.00	gr
446	62	55	200.00	gr
447	62	69	50.00	gr
448	62	74	2.00	gr
449	63	1	2.00	ml
450	63	33	5.00	gr
451	63	40	5.00	gr
452	63	55	200.00	gr
453	63	69	50.00	gr
454	63	74	2.00	gr
455	63	85	54.00	gr
456	64	1	2.00	ml
457	64	2	6.00	gr
458	64	33	5.00	gr
459	64	40	5.00	gr
460	64	55	200.00	gr
461	64	69	50.00	gr
462	64	74	2.00	gr
463	65	1	2.00	ml
464	65	33	5.00	gr
465	65	40	5.00	gr
466	65	55	200.00	gr
467	65	69	50.00	gr
468	65	74	2.00	gr
469	66	1	2.00	ml
470	66	33	5.00	gr
471	66	40	5.00	gr
472	66	55	200.00	gr
473	66	61	24.00	gr
474	66	69	50.00	gr
475	66	74	2.00	gr
476	67	1	3.00	ml
477	67	6	60.00	gr
478	67	11	22.00	gr
479	67	73	15.00	gr
480	67	74	2.00	gr
481	97	1	5.00	ml
482	97	4	1.00	gr
483	97	11	33.00	gr
484	97	51	0.10	gr
485	97	61	1.00	gr
486	97	66	94.00	gr
487	97	73	5.00	gr
488	97	74	2.00	gr
489	97	76	20.00	gr
490	97	84	22.00	gr
491	98	1	8.00	ml
492	98	4	1.00	gr
493	98	11	33.00	gr
494	98	18	15.00	ml
495	98	26	3.00	gr
496	98	60	5.00	gr
497	98	61	1.00	gr
498	98	66	94.00	gr
499	98	74	2.00	gr
500	98	77	2.00	gr
501	98	84	22.00	gr
502	99	1	5.00	ml
503	99	18	20.00	ml
504	99	26	80.00	gr
506	99	33	10.00	gr
507	99	40	20.00	gr
508	99	65	180.00	gr
509	99	73	5.00	gr
510	99	74	2.00	gr
511	100	1	8.00	ml
512	100	4	1.00	gr
513	100	5	1.00	gr
514	100	11	22.00	gr
515	100	14	30.00	gr
516	100	61	1.00	gr
517	100	66	94.00	gr
518	100	74	2.00	gr
519	100	76	10.00	gr
520	100	80	54.00	gr
521	116	1	15.00	ml
522	116	7	20.00	gr
523	116	11	22.00	gr
524	116	28	50.00	gr
525	116	55	282.00	gr
526	116	61	1.00	gr
527	116	74	2.00	gr
528	101	1	10.00	ml
529	101	26	8.00	gr
530	101	28	50.00	gr
531	101	74	2.00	gr
532	101	84	112.00	gr
533	117	1	50.00	ml
534	117	11	33.00	gr
535	117	28	50.00	gr
536	117	55	282.00	gr
537	117	66	94.00	gr
538	117	74	2.00	gr
539	102	1	3.00	ml
540	102	18	15.00	ml
541	102	21	19.00	gr
542	102	40	3.00	gr
543	102	50	5.00	gr
544	102	66	118.00	gr
545	102	74	2.00	gr
546	68	1	5.00	ml
547	68	9	87.00	gr
548	68	11	22.00	gr
549	68	17	50.00	gr
550	68	26	5.00	gr
551	68	40	5.00	gr
552	68	72	30.00	gr
553	68	74	2.00	gr
554	68	84	79.00	gr
555	68	86	109.00	gr
556	118	1	5.00	ml
557	118	4	1.00	gr
558	118	6	30.00	gr
559	118	11	33.00	gr
560	118	40	5.00	gr
561	118	66	94.00	gr
562	118	72	30.00	gr
563	118	73	5.00	gr
564	118	74	2.00	gr
565	118	86	270.00	gr
566	69	7	20.00	gr
567	69	44	10.00	gr
568	69	55	282.00	gr
569	69	74	2.00	gr
570	69	84	22.00	gr
571	103	1	10.00	ml
572	103	11	33.00	gr
573	103	26	8.00	gr
574	103	28	50.00	gr
575	103	31	60.00	gr
576	119	11	67.00	gr
577	119	25	60.00	gr
578	119	28	15.00	gr
579	119	35	5.00	gr
580	119	84	34.00	gr
581	70	14	220.00	gr
582	70	18	5.00	ml
583	70	26	8.00	gr
584	70	33	8.00	gr
585	70	40	5.00	gr
586	70	74	2.00	gr
587	120	1	8.00	ml
588	120	4	1.00	gr
589	120	7	10.00	gr
590	120	11	56.00	gr
591	120	55	235.00	gr
592	120	57	80.00	gr
593	120	61	1.00	gr
594	120	74	2.00	gr
595	120	76	10.00	gr
596	120	84	22.00	gr
597	71	33	10.00	gr
598	71	40	5.00	gr
599	71	55	40.00	gr
600	71	63	40.00	gr
601	71	74	2.00	gr
602	72	1	4.00	ml
603	72	55	282.00	gr
604	72	74	2.00	gr
605	121	1	5.00	ml
606	121	6	15.00	gr
607	121	10	0.30	gr
608	121	11	22.00	gr
609	121	35	80.00	gr
610	121	61	1.00	gr
611	121	74	2.00	gr
612	121	84	22.00	gr
613	121	85	43.00	gr
614	123	1	5.00	ml
615	123	4	1.00	gr
616	123	5	1.00	gr
617	123	10	0.30	gr
618	123	11	22.00	gr
619	123	14	80.00	gr
620	123	64	80.00	gr
621	123	65	20.00	gr
622	123	74	2.00	gr
623	123	85	54.00	gr
624	125	1	8.00	ml
625	125	3	31.00	gr
626	125	6	15.00	gr
627	125	7	10.00	gr
628	125	11	22.00	gr
629	125	14	10.00	gr
630	125	55	176.00	gr
631	125	59	1.00	gr
632	125	61	1.00	gr
633	125	66	94.00	gr
634	125	74	2.00	gr
635	125	84	22.00	gr
636	125	85	33.00	gr
637	126	1	8.00	ml
638	126	3	38.00	gr
639	126	11	22.00	gr
640	126	14	10.00	gr
641	126	55	235.00	gr
642	126	59	1.00	gr
643	126	61	1.00	gr
644	126	65	10.00	gr
645	126	66	71.00	gr
646	126	74	2.00	gr
647	126	84	22.00	gr
648	126	85	54.00	gr
649	127	1	8.00	ml
650	127	4	1.00	gr
651	127	11	22.00	gr
652	127	22	15.00	gr
653	127	51	0.10	gr
654	127	52	130.00	gr
655	127	55	118.00	gr
656	127	59	1.00	gr
657	127	61	1.00	gr
658	127	65	20.00	gr
659	127	74	2.00	gr
660	127	84	22.00	gr
661	127	85	54.00	gr
662	128	1	8.00	ml
663	128	4	1.00	gr
664	128	11	33.00	gr
665	128	43	80.00	gr
666	128	51	0.10	gr
667	128	61	1.00	gr
668	128	66	59.00	gr
669	128	72	30.00	gr
670	128	74	2.00	gr
671	128	76	40.00	gr
672	128	84	34.00	gr
673	129	1	8.00	ml
674	129	4	1.00	gr
675	129	6	70.00	gr
676	129	7	20.00	gr
677	129	11	22.00	gr
678	129	61	1.00	gr
679	129	74	1.00	gr
680	129	79	120.00	gr
681	129	80	33.00	gr
682	129	84	22.00	gr
683	73	44	10.00	gr
684	73	55	282.00	gr
685	73	74	2.00	gr
686	104	1	5.00	ml
687	104	4	1.00	gr
688	104	11	11.00	gr
689	104	45	120.00	gr
690	104	61	6.00	gr
691	104	72	30.00	gr
692	104	74	1.00	gr
693	104	80	22.00	gr
694	104	84	11.00	gr
695	130	1	5.00	ml
696	130	4	1.00	gr
697	130	5	1.00	gr
698	130	10	0.30	gr
699	130	11	22.00	gr
700	130	56	100.00	gr
701	130	64	80.00	gr
702	130	74	2.00	gr
703	130	85	54.00	gr
704	131	1	3.00	ml
705	131	10	0.30	gr
706	131	11	22.00	gr
707	131	26	40.00	gr
709	131	55	176.00	gr
710	131	57	80.00	gr
711	131	59	1.00	gr
712	131	61	1.00	gr
713	131	74	2.00	gr
714	131	84	22.00	gr
715	105	1	8.00	ml
716	105	4	1.00	gr
717	105	11	33.00	gr
718	105	61	1.00	gr
719	105	74	2.00	gr
720	105	81	120.00	gr
721	105	84	34.00	gr
722	106	1	50.00	ml
723	106	26	10.00	gr
725	106	30	13.00	ml
726	106	45	120.00	gr
727	106	59	1.00	gr
728	106	74	1.00	gr
729	107	1	5.00	ml
730	107	11	22.00	gr
732	107	31	80.00	gr
733	107	33	5.00	gr
734	107	54	20.00	gr
735	107	59	1.00	gr
736	107	74	1.00	gr
737	108	1	5.00	ml
738	108	4	1.00	gr
739	108	11	22.00	gr
740	108	27	84.00	gr
741	108	61	1.00	gr
742	108	74	2.00	gr
743	108	76	10.00	gr
744	108	84	22.00	gr
745	1	8	65.00	gr
746	1	23	55.00	gr
747	1	32	20.00	gr
748	2	8	65.00	gr
749	2	23	55.00	gr
750	2	83	120.00	gr
751	3	39	50.00	gr
752	3	49	59.00	gr
753	3	62	63.00	gr
754	3	78	50.00	gr
755	4	8	50.00	gr
756	4	32	20.00	gr
757	4	62	63.00	gr
758	5	32	20.00	gr
759	5	39	50.00	gr
760	5	78	50.00	gr
761	6	39	50.00	gr
762	6	78	50.00	gr
763	6	83	120.00	gr
764	7	8	50.00	gr
765	7	15	5.00	gr
766	7	32	20.00	gr
767	7	39	50.00	gr
768	8	8	20.00	gr
769	8	32	20.00	gr
770	8	62	31.00	gr
771	9	24	30.00	gr
772	9	53	13.00	gr
773	9	71	30.00	gr
774	10	54	100.00	gr
775	10	72	60.00	gr
776	10	76	5.00	gr
777	10	80	22.00	gr
778	10	51	0.10	gr
779	11	28	10.00	gr
780	11	53	7.00	gr
781	11	54	100.00	gr
782	11	74	1.00	gr
783	12	53	27.00	gr
784	12	54	100.00	gr
785	12	74	1.00	gr
786	13	46	20.00	gr
787	13	54	100.00	gr
788	14	54	100.00	gr
789	14	70	10.00	gr
790	14	80	16.00	gr
791	15	28	25.00	gr
792	15	54	100.00	gr
793	15	74	1.00	gr
794	16	54	100.00	gr
795	16	58	13.00	gr
796	16	71	10.00	gr
797	16	74	1.00	gr
798	17	1	5.00	ml
799	17	24	30.00	gr
800	17	28	50.00	gr
801	17	74	1.00	gr
802	17	80	16.00	gr
803	18	23	11.00	gr
804	18	54	100.00	gr
805	18	70	15.00	gr
806	19	37	10.00	gr
807	19	54	100.00	gr
808	19	62	0.00	gr
809	20	8	50.00	gr
810	20	28	25.00	gr
811	20	32	8.00	gr
812	20	47	5.00	gr
813	20	62	31.00	gr
814	21	53	7.00	gr
815	21	54	100.00	gr
816	21	57	20.00	gr
817	22	28	25.00	gr
818	22	54	100.00	gr
819	22	74	1.00	gr
820	23	54	100.00	gr
821	23	72	30.00	gr
822	24	29	30.00	gr
823	24	54	100.00	gr
824	25	38	20.00	gr
825	25	54	100.00	gr
826	26	47	20.00	gr
827	26	54	100.00	gr
828	27	11	11.00	gr
829	27	30	7.00	ml
830	27	31	20.00	gr
831	27	54	100.00	gr
832	28	1	5.00	ml
833	28	24	30.00	gr
834	28	25	40.00	gr
835	28	74	1.00	gr
836	29	83	10.00	gr
837	29	80	11.00	gr
838	29	53	7.00	gr
839	29	63	10.00	gr
840	29	14	10.00	gr
841	29	42	70.00	gr
842	29	74	1.00	gr
843	29	1	5.00	ml
844	29	59	1.00	gr
845	29	66	24.00	gr
846	29	51	0.10	gr
847	30	72	30.00	gr
848	30	11	22.00	gr
849	30	80	22.00	gr
850	30	86	54.00	gr
851	30	13	27.00	gr
852	30	74	1.00	gr
853	30	1	5.00	ml
854	30	41	50.00	gr
855	30	28	5.00	gr
51	74	28	25.00	gr
61	75	28	20.00	gr
72	76	28	20.00	gr
99	35	28	10.00	gr
161	78	28	25.00	gr
178	80	28	50.00	gr
230	87	28	20.00	gr
239	88	28	50.00	gr
252	89	28	20.00	gr
265	46	28	20.00	gr
271	47	28	20.00	gr
304	92	28	25.00	gr
505	99	28	25.00	gr
708	131	28	13.00	gr
724	106	28	13.00	gr
731	107	28	33.00	gr
873	138	8	30.00	gr
874	138	32	20.00	gr
\.


--
-- Data for Name: recetas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recetas (id_receta, nombre, id_tipo_comida, estado, created_at, updated_at) FROM stdin;
1	Avena con leche y fruta	1	1	2025-11-16 22:40:27.461193	2025-11-16 22:40:27.461193
2	Yogur natural con frutas y avena	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
3	Ensalada de frutas con chía	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
4	Avena cocida con plátano	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
5	Pudín de fruta	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
6	Yogurt con chía y fruta	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
7	Porridge avena	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
8	Smoothie de fruta y avena	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
9	Galletas con queso fresco	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
10	Pizza napolitana	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
11	Pan palta huevo	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
12	Pan con palta	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
13	Pan con mermelada	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
14	Pan quesillo - tomate	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
15	Pan pasta de huevo	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
16	Pan queso fresco - pepino	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
17	Galletas omelette tomate	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
18	Pan quesillo - frutilla	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
19	Pan con mantequilla de maní y plátano	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
20	Panqueques de avena y platano	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
21	Pan con pasta de pollo y palta	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
22	Pan huevo revuelto	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
23	Pan con queso	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
24	Pan con jamón	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
25	Pan con manjar	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
26	Pan con miel	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
27	Pan con jurel	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
28	Galletas humus	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
29	Fajitas	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
30	Empanadas de verduras	1	1	2025-11-16 22:42:24.636293	2025-11-16 22:42:24.636293
31	Acelgas a la crema	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
32	Arroz arabe	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
33	Arroz campesino	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
34	Arroz cebollin	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
35	Arroz chaufan	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
36	Arroz curry	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
37	Arroz graneado	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
38	Arroz olivo	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
39	Arroz perla	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
40	Arroz piamontesa	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
41	Arroz primavera	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
42	Arroz tartaro	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
43	Arroz verde	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
44	Charquican de verduras	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
45	Ensalada arroz	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
46	Fritos de acelga	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
47	Fritos de coliflor	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
48	Guiso de verduras	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
49	Papas doradas	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
50	Papas fritas	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
51	Papas gratinadas	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
52	Papas provenzal	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
53	Pasta a la crema	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
54	Pasta a la zanahoria	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
55	Pasta al pesto	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
56	Pasta atomatada	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
57	Pasta cocida	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
58	Pasta con verdura salteada	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
59	Ensalada york	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
60	Pastas gratinadas	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
61	Pastas piamontesa	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
62	Pure florentino	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
63	Pure mixto	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
64	Pure oliva	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
65	Pure papas	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
66	Pure piamontesa	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
67	Risotto blanco	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
68	Verduras gratinadas	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
69	Ensalada papa (rusa)	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
70	Choclo a la crema	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
71	Pure de legumbres	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
72	Papas cocidas	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
73	Papas con mayonesa	2	1	2025-11-16 22:44:59.911213	2025-11-16 22:44:59.911213
74	Ají de gallina	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
75	Albóndigas de carne	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
76	Albóndigas en salsa	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
77	Arvejado de vacuno	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
78	Asado alemán	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
79	Asado de vacuno al horno	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
80	Budín de verduras	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
81	Carne a la cacerola	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
82	Carne en salsa española	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
83	Carne mechada	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
84	Carne mongoliana	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
85	Chapsui de vacuno	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
86	Pulpa de cerdo a la mostaza	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
87	Croquetas de carne al horno	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
88	Croquetas de legumbres	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
89	Escalopa kaiser	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
90	Filetitos de pollo grillado	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
91	Goulash de vacuno	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
92	Guiso de verduras con carne	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
93	Pescado a la plancha	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
94	Pollo apanado	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
95	Pollo asado	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
96	Pollo mediterraneo	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
97	Salsa italiana	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
98	Strogonoff de vacuno	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
99	Tartaleta de verduras	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
100	Tomatican	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
101	Tortilla de verduras	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
102	Vacuno relleno con espinaca	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
103	Tortilla de jurel	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
104	Cancato de merluza	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
105	Pollo al jugo	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
106	Pescado frito	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
107	Budín de jurel	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
108	Panita al jugo	3	1	2025-11-16 22:46:28.275731	2025-11-16 22:46:28.275731
109	Arroz criollo	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
110	Ajiaco	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
111	Lasaña blanca de ave	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
112	Pasta Bontoux	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
113	Pastel de papas	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
114	Caldillo de pescado	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
115	Porotos con riendas	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
116	Tortilla de papas	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
117	Vacuno a lo pobre	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
118	Zapallo italiano relleno con carne	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
119	Ensalada tibia de legumbres con huevo	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
120	Estofado	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
121	Lentejas guisadas	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
122	Porotos con mote	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
123	Porotos con pilco	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
124	Pastel de choclo	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
125	Carbonada	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
126	Charquicán	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
127	Cazuela	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
128	Lasaña boloñesa	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
129	Paella	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
130	Porotos con mazamorra	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
131	Pantrucas	4	1	2025-11-16 22:48:57.262115	2025-11-16 22:48:57.262115
138	Prueba 1	1	0	2026-02-17 02:03:24.818102	2026-02-17 02:25:50.921591
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id_rol, nombre, descripcion) FROM stdin;
1	Encargado de TI	Acceso total al sistema 
2	Nutricionista	Puede gestionar recetas y informes
3	Usuario Estándar	Acceso básico como lectura de recetas y calculo de porciones.
\.


--
-- Data for Name: tipos_comida; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipos_comida (id_tipo_comida, nombre) FROM stdin;
1	Desayuno u Once
2	Almuerzo o Cena-Acompañamiento
3	Almuerzo o Cena-Proteína
4	Almuerzo o Cena-Plato Compuesto
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id_usuario, nombre, correo, password_hash, id_rol, estado, created_at) FROM stdin;
3	Monserrat Pedraza	monserrat.pedraza@coanil.cl	pbkdf2_sha256$1000000$nF37NAXHK1I8LGAGdNKUWf$XtCc/P+1d8YzKE6ozuXilPD7utTCKWIoBTV/+1ultZE=	3	1	2025-12-02 05:19:17.539166
4	pedrito	pedrito@coanil.cl	pbkdf2_sha256$1000000$Ak9gn3sY6ZTtRUyuOYkwYO$cLtniQTX/KjSHqjzkupvikJ6y/DJL/8vzcRCaJ16LT0=	1	1	2025-12-02 02:32:10.431107
2	Benjamin Salazar	benjamin.salazar@coanil.cl	pbkdf2_sha256$1000000$FbS6l4zNUNKJ9HX1J6Jl8X$yIqm2S1wIZzlEb3lk99xn08V7E7J5Kyk/NdurUMPzOI=	1	1	2025-11-30 21:42:30.152023
1	Oriana Lagos	oriana.lagos@coanil.cl	pbkdf2_sha256$1000000$8a7D9FnJ1jOb5QUoVepKnk$U0KGhOwT4UzHJt33Suzedvm9ItInQA4lXtkN3lYU+f8=	2	1	2025-11-30 21:33:31.596741
5	Irma Pinochet	irma.pinochet@coanil.cl		3	1	2026-02-18 02:43:32.214841
6	Alonso Rojas	alonso.rojas@coanil.cl		3	1	2026-02-18 02:43:49.502588
7	Patricia Cuevas	patricia.cuevas@coanil.cl		3	1	2026-02-18 02:44:07.592193
8	Paz Donoso	paz.donoso@coanil.cl		3	1	2026-02-18 02:44:21.35523
9	Juanita Velez	juanita.velez@coanil.cl		3	1	2026-02-18 02:44:41.17465
10	Cecilia Gomez	cgomez@coanil.cl		3	1	2026-02-18 02:44:59.189348
11	Milena Lizana	milena.lizana@coanil.cl		3	1	2026-02-18 02:45:12.627638
12	Alvaro Pizarro	alvaro.pizarro@coanil.cl		3	1	2026-02-18 02:45:30.934915
13	Gabriela Aravena	gabriela.aravena@coanil.cl		3	1	2026-02-18 02:45:48.935688
14	Valentina Tapia	valentina.tapia@coanil.cl		3	1	2026-02-18 02:46:03.852758
15	Laura Llancao	laura.llancao@coanil.cl		3	1	2026-02-18 02:46:21.438372
16	Tamara Sepulveda	tamara.sepulveda@coanil.cl		3	1	2026-02-18 02:46:38.14819
17	Ruth Ramos	ruth.ramos@coanil.cl		3	1	2026-02-18 02:46:59.342091
18	Angela Araya	angela.araya@coanil.cl		3	1	2026-02-18 02:47:13.933918
19	Residencia Camelias	uacamelias@coanil.cl		3	1	2026-02-18 02:47:29.296969
20	Enry Echeverria	enry.echverria@coanil.cl		3	1	2026-02-18 02:47:48.315425
21	Cristian Rivera	cristian.rivera@coanil.cl		3	1	2026-02-18 02:48:05.308926
22	Residencia Las Azaleas	ualasazaleas@coanil.cl		3	1	2026-02-18 02:48:26.020115
23	Norma Garrido	norma.garridor@coanil.cl		3	1	2026-02-18 02:48:47.421295
24	Norma Villarroel	norma.villarroel@coanil.cl		3	1	2026-02-18 02:49:14.005757
25	Valentina Aravena	valentina.aravena@coanil.cl		2	1	2026-02-18 02:49:30.39176
26	Carla Galdames	carla.galdames@coanil.cl		2	1	2026-02-18 02:49:44.918246
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 88, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 22, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- Name: ingredientes_id_ingrediente_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ingredientes_id_ingrediente_seq', 86, true);


--
-- Name: receta_ingredientes_id_receta_ingrediente_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.receta_ingredientes_id_receta_ingrediente_seq', 874, true);


--
-- Name: recetas_id_receta_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recetas_id_receta_seq', 138, true);


--
-- Name: roles_id_rol_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_rol_seq', 3, true);


--
-- Name: tipos_comida_id_tipo_comida_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipos_comida_id_tipo_comida_seq', 4, true);


--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_usuario_seq', 26, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: ingredientes ingredientes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ingredientes
    ADD CONSTRAINT ingredientes_pkey PRIMARY KEY (id_ingrediente);


--
-- Name: receta_ingredientes receta_ingredientes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.receta_ingredientes
    ADD CONSTRAINT receta_ingredientes_pkey PRIMARY KEY (id_receta_ingrediente);


--
-- Name: recetas recetas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recetas
    ADD CONSTRAINT recetas_pkey PRIMARY KEY (id_receta);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id_rol);


--
-- Name: tipos_comida tipos_comida_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipos_comida
    ADD CONSTRAINT tipos_comida_pkey PRIMARY KEY (id_tipo_comida);


--
-- Name: receta_ingredientes uq_receta_ingrediente; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.receta_ingredientes
    ADD CONSTRAINT uq_receta_ingrediente UNIQUE (id_receta, id_ingrediente);


--
-- Name: usuarios usuarios_correo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_correo_key UNIQUE (correo);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: idx_receta_nombre; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_receta_nombre ON public.recetas USING btree (nombre);


--
-- Name: idx_receta_tipo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_receta_tipo ON public.recetas USING btree (id_tipo_comida);


--
-- Name: idx_usuario_correo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_usuario_correo ON public.usuarios USING btree (correo);


--
-- Name: recetas tr_update_recetas; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER tr_update_recetas BEFORE UPDATE ON public.recetas FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: receta_ingredientes fk_receta_ing_ingred; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.receta_ingredientes
    ADD CONSTRAINT fk_receta_ing_ingred FOREIGN KEY (id_ingrediente) REFERENCES public.ingredientes(id_ingrediente);


--
-- Name: receta_ingredientes fk_receta_ing_receta; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.receta_ingredientes
    ADD CONSTRAINT fk_receta_ing_receta FOREIGN KEY (id_receta) REFERENCES public.recetas(id_receta);


--
-- Name: recetas fk_recetas_tipos; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recetas
    ADD CONSTRAINT fk_recetas_tipos FOREIGN KEY (id_tipo_comida) REFERENCES public.tipos_comida(id_tipo_comida);


--
-- Name: usuarios fk_usuarios_roles; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fk_usuarios_roles FOREIGN KEY (id_rol) REFERENCES public.roles(id_rol);


--
-- PostgreSQL database dump complete
--

\unrestrict RhXobQ0y58lu7Zs2aqsNUcp7mDw5exgx8l0FKwLfQsvgxLipYK5DxFjckVVI4QL

