# Generated by Django 5.2.8 on 2025-12-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recetas',
            index=models.Index(fields=['nombre'], name='idx_receta_nombre'),
        ),
        migrations.AddIndex(
            model_name='recetas',
            index=models.Index(fields=['id_tipo_comida'], name='idx_receta_tipo_comida'),
        ),
        migrations.AddIndex(
            model_name='usuarios',
            index=models.Index(fields=['correo'], name='idx_usuario_correo'),
        ),
    ]
